version: '3.9'

services:
  nuxt:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sigecafe-nuxt-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV
      - BASE_URL
      - AUTH_SECRET
      - DATABASE_URL
      - SESSION_REFRESH_SECONDS
      - SESSION_MAX_AGE_SECONDS
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: sigecafe-postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sigecafe
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5a

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
