name: Coffee Prices Scraping

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias à meia-noite

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run scraping script
      run: npm run scrape:coffee

    - name: Configure git for GitHub Actions
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Commit and push if changed
      run: |
        git add data/coffee-prices.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update coffee prices" && git push)